/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PostId = IDL.Text;
export const CommentId = IDL.Text;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const CommentPublic = IDL.Record({
  'commentId' : CommentId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'postId' : PostId,
});
export const PostPublic = IDL.Record({
  'userId' : UserId,
  'createdAt' : Timestamp,
  'imageUrl' : IDL.Text,
  'caption' : IDL.Text,
  'commentsCount' : IDL.Nat,
  'likesCount' : IDL.Nat,
  'postId' : PostId,
});
export const FeedPage = IDL.Record({
  'nextOffset' : IDL.Opt(IDL.Nat),
  'posts' : IDL.Vec(PostPublic),
});
export const UserPublic = IDL.Record({
  'bio' : IDL.Text,
  'uid' : UserId,
  'username' : IDL.Text,
  'followersCount' : IDL.Nat,
  'email' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'followingCount' : IDL.Nat,
});
export const NotifId = IDL.Text;
export const Notification = IDL.Record({
  'notifType' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'notifId' : NotifId,
  'actorId' : UserId,
  'postId' : IDL.Opt(PostId),
});

export const idlService = IDL.Service({
  'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Text], [PostId], []),
  'followUser' : IDL.Func([UserId], [IDL.Bool], []),
  'getComments' : IDL.Func([PostId], [IDL.Vec(CommentPublic)], ['query']),
  'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [FeedPage], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPost' : IDL.Func([PostId], [IDL.Opt(PostPublic)], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
  'likePost' : IDL.Func([PostId], [IDL.Bool], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'savePost' : IDL.Func([PostId], [IDL.Bool], []),
  'unfollowUser' : IDL.Func([UserId], [IDL.Bool], []),
  'unlikePost' : IDL.Func([PostId], [IDL.Bool], []),
  'unsavePost' : IDL.Func([PostId], [IDL.Bool], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PostId = IDL.Text;
  const CommentId = IDL.Text;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const CommentPublic = IDL.Record({
    'commentId' : CommentId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'postId' : PostId,
  });
  const PostPublic = IDL.Record({
    'userId' : UserId,
    'createdAt' : Timestamp,
    'imageUrl' : IDL.Text,
    'caption' : IDL.Text,
    'commentsCount' : IDL.Nat,
    'likesCount' : IDL.Nat,
    'postId' : PostId,
  });
  const FeedPage = IDL.Record({
    'nextOffset' : IDL.Opt(IDL.Nat),
    'posts' : IDL.Vec(PostPublic),
  });
  const UserPublic = IDL.Record({
    'bio' : IDL.Text,
    'uid' : UserId,
    'username' : IDL.Text,
    'followersCount' : IDL.Nat,
    'email' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'followingCount' : IDL.Nat,
  });
  const NotifId = IDL.Text;
  const Notification = IDL.Record({
    'notifType' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'notifId' : NotifId,
    'actorId' : UserId,
    'postId' : IDL.Opt(PostId),
  });
  
  return IDL.Service({
    'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Text], [PostId], []),
    'followUser' : IDL.Func([UserId], [IDL.Bool], []),
    'getComments' : IDL.Func([PostId], [IDL.Vec(CommentPublic)], ['query']),
    'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [FeedPage], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPost' : IDL.Func([PostId], [IDL.Opt(PostPublic)], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
    'likePost' : IDL.Func([PostId], [IDL.Bool], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'savePost' : IDL.Func([PostId], [IDL.Bool], []),
    'unfollowUser' : IDL.Func([UserId], [IDL.Bool], []),
    'unlikePost' : IDL.Func([PostId], [IDL.Bool], []),
    'unsavePost' : IDL.Func([PostId], [IDL.Bool], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };