/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CommentId = string;
export interface CommentPublic {
  'commentId' : CommentId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'text' : string,
  'postId' : PostId,
}
export interface FeedPage {
  'nextOffset' : [] | [bigint],
  'posts' : Array<PostPublic>,
}
export type NotifId = string;
export interface Notification {
  'notifType' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'notifId' : NotifId,
  'actorId' : UserId,
  'postId' : [] | [PostId],
}
export type PostId = string;
export interface PostPublic {
  'userId' : UserId,
  'createdAt' : Timestamp,
  'imageUrl' : string,
  'caption' : string,
  'commentsCount' : bigint,
  'likesCount' : bigint,
  'postId' : PostId,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserPublic {
  'bio' : string,
  'uid' : UserId,
  'username' : string,
  'followersCount' : bigint,
  'email' : string,
  'avatarUrl' : string,
  'followingCount' : bigint,
}
export interface _SERVICE {
  'addComment' : ActorMethod<[PostId, string], CommentId>,
  'createPost' : ActorMethod<[string, string], PostId>,
  'followUser' : ActorMethod<[UserId], boolean>,
  'getComments' : ActorMethod<[PostId], Array<CommentPublic>>,
  'getFeed' : ActorMethod<[bigint, bigint], FeedPage>,
  'getMyProfile' : ActorMethod<[], [] | [UserPublic]>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPost' : ActorMethod<[PostId], [] | [PostPublic]>,
  'getUser' : ActorMethod<[UserId], [] | [UserPublic]>,
  'likePost' : ActorMethod<[PostId], boolean>,
  'registerUser' : ActorMethod<[string, string], boolean>,
  'savePost' : ActorMethod<[PostId], boolean>,
  'unfollowUser' : ActorMethod<[UserId], boolean>,
  'unlikePost' : ActorMethod<[PostId], boolean>,
  'unsavePost' : ActorMethod<[PostId], boolean>,
  'updateProfile' : ActorMethod<[string, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];