/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface PostPublic {
    userId: UserId;
    createdAt: Timestamp;
    imageUrl: string;
    caption: string;
    commentsCount: bigint;
    likesCount: bigint;
    postId: PostId;
}
export interface UserPublic {
    bio: string;
    uid: UserId;
    username: string;
    followersCount: bigint;
    email: string;
    avatarUrl: string;
    followingCount: bigint;
}
export interface FeedPage {
    nextOffset?: bigint;
    posts: Array<PostPublic>;
}
export type PostId = string;
export interface Notification {
    notifType: string;
    userId: UserId;
    createdAt: Timestamp;
    notifId: NotifId;
    actorId: UserId;
    postId?: PostId;
}
export interface CommentPublic {
    commentId: CommentId;
    userId: UserId;
    createdAt: Timestamp;
    text: string;
    postId: PostId;
}
export type CommentId = string;
export type NotifId = string;
export interface backendInterface {
    addComment(postId: PostId, text: string): Promise<CommentId>;
    createPost(imageUrl: string, caption: string): Promise<PostId>;
    followUser(followeeId: UserId): Promise<boolean>;
    getComments(postId: PostId): Promise<Array<CommentPublic>>;
    getFeed(offset: bigint, limit: bigint): Promise<FeedPage>;
    getMyProfile(): Promise<UserPublic | null>;
    getNotifications(): Promise<Array<Notification>>;
    getPost(postId: PostId): Promise<PostPublic | null>;
    getUser(uid: UserId): Promise<UserPublic | null>;
    likePost(postId: PostId): Promise<boolean>;
    registerUser(username: string, email: string): Promise<boolean>;
    savePost(postId: PostId): Promise<boolean>;
    unfollowUser(followeeId: UserId): Promise<boolean>;
    unlikePost(postId: PostId): Promise<boolean>;
    unsavePost(postId: PostId): Promise<boolean>;
    updateProfile(username: string, bio: string, avatarUrl: string): Promise<boolean>;
}
import type { FeedPage as _FeedPage, NotifId as _NotifId, Notification as _Notification, PostId as _PostId, PostPublic as _PostPublic, Timestamp as _Timestamp, UserId as _UserId, UserPublic as _UserPublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addComment(arg0: PostId, arg1: string): Promise<CommentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async createPost(arg0: string, arg1: string): Promise<PostId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, arg1);
            return result;
        }
    }
    async followUser(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getComments(arg0: PostId): Promise<Array<CommentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getFeed(arg0: bigint, arg1: bigint): Promise<FeedPage> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeed(arg0, arg1);
                return from_candid_FeedPage_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeed(arg0, arg1);
            return from_candid_FeedPage_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: PostId): Promise<PostPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: UserId): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async likePost(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1);
            return result;
        }
    }
    async savePost(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.savePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePost(arg0);
            return result;
        }
    }
    async unfollowUser(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async unlikePost(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return result;
        }
    }
    async unsavePost(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unsavePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsavePost(arg0);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_FeedPage_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedPage): FeedPage {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PostId]): PostId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PostPublic]): PostPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nextOffset: [] | [bigint];
    posts: Array<_PostPublic>;
}): {
    nextOffset?: bigint;
    posts: Array<PostPublic>;
} {
    return {
        nextOffset: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.nextOffset)),
        posts: value.posts
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notifType: string;
    userId: _UserId;
    createdAt: _Timestamp;
    notifId: _NotifId;
    actorId: _UserId;
    postId: [] | [_PostId];
}): {
    notifType: string;
    userId: UserId;
    createdAt: Timestamp;
    notifId: NotifId;
    actorId: UserId;
    postId?: PostId;
} {
    return {
        notifType: value.notifType,
        userId: value.userId,
        createdAt: value.createdAt,
        notifId: value.notifId,
        actorId: value.actorId,
        postId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.postId))
    };
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
